server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pet_project
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    expose-request-attributes: true
